name: Continuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
  push:
    branches:
      - master
    paths:
      - "src/**"

defaults:
  run:
    working-directory: ./src

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - name: Install Dependencies
        run: npm install
      - name: Run Test
        run: npm run test
