name: Continuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: write

defaults:
  run:
    working-directory: ./src

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Install Dependencies
        run: npm install
      - name: Run Test
        run: npm run test

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: Run Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
